pipeline:
  identifier: Build_Golang_CICD_Tutorial_1698261809230
  name: Build Golang-CICD-Tutorial
  orgIdentifier: default
  projectIdentifier: Golandcicdtuto
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698261793130
        repoName: Golang-CICD-Tutorial
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Test Go App
                  identifier: Test_Go_App
                  spec:
                    shell: Sh
                    command: |-
                      go mod init Golang-CICD-Tutorial
                      go build
                      go test
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
